import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Modal, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { EnergyHero } from '@/components/EnergyHero';
import { useAuth } from '@/lib/auth';
import { useMyPackages, useCreatePackage, useDeletePackage, useMyPackagePurchases } from '@/lib/queries/packages';
import { BRAND, spacing } from '@/lib/theme';
import { useTheme } from '@/lib/useTheme';
import type { Package, PackagePurchase } from '@/lib/types';

function CreatePackageModal({ visible, trainerId, onClose }: { visible: boolean; trainerId: string; onClose: () => void }) {
  const { colors, accent }=useTheme(); const createPackage=useCreatePackage(trainerId); const [title,setTitle]=useState(''); const [sessionCount,setSessionCount]=useState(''); const [priceDollars,setPriceDollars]=useState(''); const [description,setDescription]=useState('');
  const reset=()=>{setTitle('');setSessionCount('');setPriceDollars('');setDescription('');};
  const handleCreate=async()=>{const count=parseInt(sessionCount,10);const price=parseFloat(priceDollars);if(!title.trim())return Alert.alert('Title required');if(!Number.isFinite(count)||count<1)return Alert.alert('Invalid sessions');if(!Number.isFinite(price)||price<0)return Alert.alert('Invalid price');try{await createPackage.mutateAsync({title:title.trim(),session_count:count,price_cents:Math.round(price*100),description:description.trim()||null,is_active:true});reset();onClose();}catch(e:unknown){Alert.alert('Error',e instanceof Error?e.message:'Unknown error');}};
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={[styles.modalSafe,{backgroundColor:colors.background}]}><View style={[styles.modalHeader,{borderBottomColor:colors.border}]}><TouchableOpacity onPress={()=>{reset();onClose();}}><Text style={{color:colors.muted}}>Cancel</Text></TouchableOpacity><Text style={[styles.modalTitle,{color:colors.ink}]}>Create package</Text><TouchableOpacity onPress={handleCreate} disabled={createPackage.isPending}>{createPackage.isPending?<ActivityIndicator/>:<Text style={{color:accent,fontWeight:'900'}}>Create</Text>}</TouchableOpacity></View><ScrollView contentContainerStyle={styles.modalContent}><FormLabel text="PACKAGE NAME" colors={colors}/><TextInput style={[styles.input,{borderColor:colors.borderInput,color:colors.ink,backgroundColor:colors.surfaceCard}]} value={title} onChangeText={setTitle} placeholder="5-session starter" placeholderTextColor={colors.placeholder}/><View style={styles.twoCol}><View style={{flex:1}}><FormLabel text="SESSIONS" colors={colors}/><TextInput style={[styles.input,{borderColor:colors.borderInput,color:colors.ink,backgroundColor:colors.surfaceCard}]} value={sessionCount} onChangeText={setSessionCount} keyboardType="number-pad" placeholder="5" placeholderTextColor={colors.placeholder}/></View><View style={{flex:1}}><FormLabel text="TOTAL USD" colors={colors}/><TextInput style={[styles.input,{borderColor:colors.borderInput,color:colors.ink,backgroundColor:colors.surfaceCard}]} value={priceDollars} onChangeText={setPriceDollars} keyboardType="decimal-pad" placeholder="250" placeholderTextColor={colors.placeholder}/></View></View><FormLabel text="DESCRIPTION" colors={colors}/><TextInput style={[styles.input,styles.multiline,{borderColor:colors.borderInput,color:colors.ink,backgroundColor:colors.surfaceCard}]} value={description} onChangeText={setDescription} multiline placeholder="What’s included…" placeholderTextColor={colors.placeholder}/></ScrollView></SafeAreaView></Modal>;
}
function FormLabel({text,colors}:{text:string;colors:ReturnType<typeof useTheme>['colors']}){return <Text style={[styles.label,{color:colors.muted}]}>{text}</Text>;}

function TrainerPackageCard({pkg,trainerId}:{pkg:Package;trainerId:string}){const{colors,accent}=useTheme();const del=useDeletePackage(trainerId);const per=pkg.session_count?(pkg.price_cents/pkg.session_count/100).toFixed(2):'—';const handleDelete=()=>Alert.alert('Delete package?',`“${pkg.title}” will be removed.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await del.mutateAsync(pkg.id);}catch(e:unknown){Alert.alert('Error',e instanceof Error?e.message:'Unknown error');}}}]);return <View style={[styles.card,{backgroundColor:colors.surfaceCard,borderColor:colors.border}]}><View style={[styles.cardRail,{backgroundColor:accent}]}/><View style={{flex:1}}><Text style={[styles.cardEyebrow,{color:accent}]}>{pkg.session_count} SESSION PACKAGE</Text><Text style={[styles.packageTitle,{color:colors.ink}]}>{pkg.title}</Text><Text style={[styles.packageMeta,{color:colors.muted}]}>${per}/session</Text>{pkg.description?<Text style={[styles.packageDesc,{color:colors.muted}]}>{pkg.description}</Text>:null}</View><View style={styles.priceSide}><Text style={[styles.packagePrice,{color:colors.ink}]}>${(pkg.price_cents/100).toFixed(0)}</Text><TouchableOpacity onPress={handleDelete}>{del.isPending?<ActivityIndicator size="small"/>:<Ionicons name="trash-outline" size={16} color={colors.danger}/>}</TouchableOpacity></View></View>;}
function PurchaseCard({purchase}:{purchase:PackagePurchase}){const{colors,accent}=useTheme();const total=purchase.package?.session_count??0;const remaining=purchase.sessions_remaining;const used=Math.max(0,total-remaining);const pct=total?Math.min(100,(used/total)*100):0;return <View style={[styles.card,{backgroundColor:colors.surfaceCard,borderColor:colors.border}]}><View style={[styles.cardRail,{backgroundColor:BRAND.blue}]}/><View style={{flex:1}}><Text style={[styles.cardEyebrow,{color:accent}]}>ACTIVE PACKAGE</Text><Text style={[styles.packageTitle,{color:colors.ink}]}>{purchase.package?.title??'Package'}</Text><Text style={[styles.packageMeta,{color:colors.muted}]}>{remaining} of {total} sessions remaining</Text><View style={[styles.progressTrack,{backgroundColor:colors.border}]}><View style={[styles.progressFill,{backgroundColor:accent,width:`${pct}%`}]}/></View></View></View>;}

export default function Packages(){const{session,profile}=useAuth();const userId=session?.user.id??'';const isTrainer=profile?.role==='trainer';const{colors,accent}=useTheme();const[show,setShow]=useState(false);const trainerQ=useMyPackages(isTrainer?userId:undefined);const clientQ=useMyPackagePurchases(!isTrainer?userId:undefined);const loading=isTrainer?trainerQ.isLoading:clientQ.isLoading;const fetching=isTrainer?trainerQ.isFetching:clientQ.isFetching;const refetch=isTrainer?trainerQ.refetch:clientQ.refetch;if(loading)return <View style={[styles.center,{backgroundColor:colors.background}]}><ActivityIndicator/></View>;
  if(isTrainer){const packages=trainerQ.data??[];return <SafeAreaView style={[styles.safe,{backgroundColor:colors.background}]} edges={['bottom']}><FlatList data={packages} keyExtractor={p=>p.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={fetching} onRefresh={refetch}/>} ListHeaderComponent={<><EnergyHero eyebrow="SELL YOUR VALUE" title="Packages" subtitle="Bundle sessions into clear offers clients can understand and return to." icon="layers-outline" compact/><View style={styles.sectionRow}><Text style={[styles.sectionTitle,{color:colors.ink}]}>{packages.length} offers</Text><View style={styles.sectionBeam}/></View></>} renderItem={({item})=><TrainerPackageCard pkg={item} trainerId={userId}/>} ListEmptyComponent={<View style={[styles.empty,{borderColor:colors.border}]}><Ionicons name="layers-outline" size={26} color={accent}/><Text style={[styles.emptyTitle,{color:colors.ink}]}>No packages yet.</Text><Text style={{color:colors.muted,fontSize:12}}>Create a simple bundle clients can buy again.</Text></View>}/><TouchableOpacity style={styles.addBtn} onPress={()=>setShow(true)}><Ionicons name="add" size={17} color="#fff"/><Text style={styles.addText}>Create package</Text></TouchableOpacity><CreatePackageModal visible={show} trainerId={userId} onClose={()=>setShow(false)}/></SafeAreaView>;}
  const purchases=clientQ.data??[];return <SafeAreaView style={[styles.safe,{backgroundColor:colors.background}]} edges={['bottom']}><FlatList data={purchases} keyExtractor={p=>p.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={fetching} onRefresh={refetch}/>} ListHeaderComponent={<><EnergyHero eyebrow="YOUR COMMITMENT" title="My packages" subtitle="See the sessions you’ve purchased and how much of each path remains." icon="layers-outline" compact/><View style={styles.sectionRow}><Text style={[styles.sectionTitle,{color:colors.ink}]}>Active</Text><View style={styles.sectionBeam}/></View></>} renderItem={({item})=><PurchaseCard purchase={item}/>} ListEmptyComponent={<View style={[styles.empty,{borderColor:colors.border}]}><Text style={[styles.emptyTitle,{color:colors.ink}]}>No packages yet.</Text><Text style={{color:colors.muted,fontSize:12}}>Packages you purchase from trainers will appear here.</Text></View>}/></SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},list:{padding:spacing.md,paddingBottom:105},sectionRow:{flexDirection:'row',alignItems:'flex-end',gap:12,marginTop:24,marginBottom:11},sectionTitle:{fontSize:19,fontWeight:'900'},sectionBeam:{flex:1,height:1,backgroundColor:BRAND.blue,opacity:.22,marginBottom:5},card:{position:'relative',overflow:'hidden',flexDirection:'row',gap:14,borderWidth:1,borderRadius:14,padding:16,marginBottom:9},cardRail:{position:'absolute',left:0,top:0,bottom:0,width:3,opacity:.72},cardEyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.2},packageTitle:{fontSize:16,fontWeight:'900',marginTop:3},packageMeta:{fontSize:12,marginTop:3,fontWeight:'700'},packageDesc:{fontSize:11,lineHeight:16,marginTop:6},priceSide:{alignItems:'flex-end',justifyContent:'space-between'},packagePrice:{fontSize:22,fontWeight:'900'},progressTrack:{height:5,borderRadius:3,overflow:'hidden',marginTop:12},progressFill:{height:'100%',borderRadius:3},empty:{borderTopWidth:1,borderBottomWidth:1,paddingVertical:25,alignItems:'center',gap:5},emptyTitle:{fontSize:15,fontWeight:'900'},addBtn:{position:'absolute',right:spacing.md,bottom:spacing.lg,flexDirection:'row',alignItems:'center',gap:6,backgroundColor:BRAND.navy,borderRadius:10,paddingHorizontal:15,paddingVertical:12},addText:{color:'#fff',fontWeight:'900',fontSize:13},modalSafe:{flex:1},modalHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:spacing.md,borderBottomWidth:1},modalTitle:{fontSize:15,fontWeight:'900'},modalContent:{padding:spacing.lg},label:{fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:18,marginBottom:7},input:{borderWidth:1,borderRadius:10,paddingHorizontal:13,paddingVertical:12,fontSize:15},multiline:{minHeight:95,textAlignVertical:'top'},twoCol:{flexDirection:'row',gap:10}});
