alter table public.bookings add column if not exists virtual_meeting_provider text;
alter table public.bookings add column if not exists virtual_meeting_url text;
alter table public.bookings add column if not exists virtual_meeting_external_id text;

comment on column public.bookings.virtual_meeting_provider is 'Provider used for a virtual training session, e.g. google_meet or zoom.';
comment on column public.bookings.virtual_meeting_url is 'Join URL generated by the configured virtual-session provider.';
comment on column public.bookings.virtual_meeting_external_id is 'Provider-side meeting identifier used for idempotent updates/cancellation.';
